### ISSUE TITLE
Issue with secret.ts 

### ISSUE THREAD

**Issue by spaceincase** [paco0x/amm-arbitrageur#2]
I input my public and private keys both with and without quotes and either way i keep getting the same error. What format should i be using?

`Error: network does not support ENS (operation="ENS", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.1.0)`

**Comment by paco0x** [comment]
https://github.com/paco0x/amm-arbitrageur/blob/master/.secret.ts.sample

**Comment by paco0x** [comment]
If you are using `deploy.ts` script, please try with the latest code. There's a fix related to the deployer address.

**Comment by sbrfarhadi** [comment]
I clone sourse code
and set bsc wallet in .secret.ts
after use this command in command promt (windows 10)
`yarn run bot
`
I have  this error:

```
Error: network does not support ENS (operation="ENS", network="bnb", code=UNSUPPORTED_OPERATION, version=providers/5.2.0)
    at Logger.makeError (,amm-arbitrageur\node_modules\@ethersproject\logger\src.ts\index.ts:213:28)
    at Logger.throwError (,amm-arbitrageur\node_modules\@ethersproject\logger\src.ts\index.ts:225:20)
    at EthersProviderWrapper.<anonymous> (,amm-arbitrageur\node_modules\@ethersproject\providers\src.ts\base-provider.ts:1513:20)
    at step (,amm-arbitrageur\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (,amm-arbitrageur\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)
    at fulfilled (,amm-arbitrageur\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  reason: 'network does not support ENS',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'ENS',
  network: 'bnb',
  level: '\x1B[34mdebug\x1B[39m',
  timestamp: '2021-05-29 16:26:39',
  [Symbol(level)]: 'debug',
  [Symbol(message)]: '2021-05-29 16:26:39 \x1B[34mdebug\x1B[39m: network does not support ENS (operation="ENS", network="bnb", code=UNSUPPORTED_OPERATION, version=providers/5.2.0) '
}
```
