### ISSUE TITLE
Error: call revert exception method getProfit(address,address)

### ISSUE THREAD

**Issue by sbrfarhadi** [paco0x/amm-arbitrageur#24]
I clone sourse code
and set bsc wallet in .secret.ts

depoly flashBot contract with remix editor and set contract address in config.ts

after use this command in command promt (windows 10)
yarn run bot
I have this error:

```

Error: call revert exception (method="getProfit(address,address)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.2.0)
    at Logger.makeError (\amm-arbitrageur\node_modules\@ethersproject\logger\src.ts\index.ts:213:28)
    at Logger.throwError (\amm-arbitrageur\node_modules\@ethersproject\logger\src.ts\index.ts:225:20)
    at Interface.decodeFunctionResult (\amm-arbitrageur\node_modules\@ethersproject\abi\src.ts\interface.ts:384:23)
    at Contract.<anonymous> (\amm-arbitrageur\node_modules\@ethersproject\contracts\src.ts\index.ts:321:44)
    at step (\amm-arbitrageur\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (\amm-arbitrageur\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (\amm-arbitrageur\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getProfit(address,address)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: ' my contract address',
  args: [
    '0xaeBE45E3a03B734c68e5557AE04BFC76917B4686',
    '0x52AaEF46c9F02dBC45Ce3a55ff2B7057f5aB6275'
  ],
  transaction: {
    data: '0x759eee10000000000000000000000000aebe45e3a03b734c68e5557ae04bfc76917b468600000000000000000000000052aaef46c9f02dbc45ce3a55ff2b7057f5ab6275',
    to: my contract address,
    from: my wallet address
  }
}
```

**Comment by sbrfarhadi** [comment]
I deploy FlashBot with 
[this link](https://github.com/paco0x/amm-arbitrageur#deploy-the-contract
)
`npx hardhat run scripts/deploy.ts --network bsc`

and change contract address in config.ts

The above problem was solved
The robot checked several token profit and then show this error

```

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"_isProviderError":true,"data":"0x

 reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: No base token in pair


```
Should the contract include bnb?

What is the minimum balance for my wallet?

**Comment by snollygolly** [comment]
I have a similar problem, when I turn on debugging, my console if filled with this:

```
2021-05-30 15:34:01 debug: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"_isProviderError":true,"data":"0x..."}, method="call", transaction={"from":"0x...","to":"0x...","data":"0x...","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.2.0) 
```

**Comment by androidexplained** [comment]
@paco0x Could you check this out? Basically you can do so by running the project!
Thanks!

**Comment by ktorrentk** [comment]
@sbrfarhadi  Hi did you get answer about contract include BNB? It is or it not
